version: "3.3"

services:
  db:
    image: andresvidal/rpi3-mongodb3
    networks:
      - ampnadorpi-noauth
    ports:
      - 27017:27017

  ampserv:
    image: ampnadorpi-noauth:0.1
    build: .
    environment:
      - AMP_PROGRAM_PATH=/home/pi/Desktop/Ampnado
      - AMP_AMPDB_ADDR=mongodb://db:27017/ampnadoDB
      - AMP_VIEWSDB_ADDR=mongodb://db:27017/ampviewsDB
      - AMP_PICDB_ADDR=mongodb://db:27017/picdb
      - AMP_SETUP=1
      - AMP_MEDIA_PATH=/usr/src/ampnado/Music
      - AMP_HTTP_THUMBNAIL_DIR_PATH=/static/images/thumbnails
      - AMP_THUMBNAIL_DIR_PATH=./static/images/thumbnails
      - AMP_NO_ART_PIC_PATH=./static/images/noartpic.jpg
      - AMP_SERVER_ADDR=http://192.168.1.26
      - AMP_SERVER_PORT=6789
      - AMP_OFFSET_SIZE=45
      - AMP_USERNAME=admin
      - AMP_PASSWORD=ampnado
    networks:
      - ampnadorpi-noauth
    ports:
      - 6789:6789
    volumes:
      - ampnadorpi-noauthvol:/usr/src/ampnado/Music
    depends_on:
      - db

networks:
  ampnadorpi-noauth:

volumes:
  ampnadorpi-noauthvol:
    driver: local
    driver_opts:
      type: none
#THIS NEEDS TO BE CHANGE TO THE CORRECT PATH ON THE PI
      device: /home/pi/Music
      o: bind
